stages:
  pull-recent-tracks:
    cmd: python scripts/hands-free/log_recent_plays.py data/raw/play_history.csv
    deps:
      - scripts/hands-free/log_recent_plays.py
    outs:
      - data/raw/play_history.csv:
          persist: true
    always_changed: true
  pull-library:
    cmd: python scripts/hands-free/pull_library.py data/raw/library.csv
    deps:
      - scripts/hands-free/pull_library.py
    outs:
      - data/raw/library.csv
    always_changed: true
