stages:
  pull-recent-tracks:
    cmd: python scripts/hands-free/log_recent_plays.py data/raw/play_history.csv
    deps:
      - scripts/hands-free/log_recent_plays.py
    outs:
      - data/raw/play_history.csv:
          persist: true
    always_changed: true
  pull-library:
    cmd: python scripts/hands-free/pull_library.py data/raw/library.csv
    deps:
      - scripts/hands-free/pull_library.py
    outs:
      - data/raw/library.csv
    always_changed: true
  pull-audio-features:
    cmd: python scripts/hands-free/pull_audio_features.py data/raw/library.csv data/raw/audio_features.csv
    deps:
      - scripts/hands-free/pull_audio_features.py
      - data/raw/library.csv
    outs:
      - data/raw/audio_features.csv:
          persist: true
  pull-artists:
    cmd: python scripts/hands-free/pull_artists.py data/raw/library.csv data/raw/artists.csv
    deps:
      - scripts/hands-free/pull_audio_features.py
      - data/raw/library.csv
    outs:
      - data/raw/artists.csv:
          persist: true
  build-root-playlists:
    foreach: ${hands-free-playlists}
    do:
      cmd: python scripts/hands-free/make_root_playlist.py "playlists/${item}.yaml" data/raw/library.csv data/raw/audio_features.csv data/raw/artists.csv "data/processed/${item}.csv"
      deps:
        - scripts/hands-free/make_root_playlist.py
        - "playlists/${item}.yaml"
        - data/raw/library.csv
        - data/raw/audio_features.csv
        - data/raw/artists.csv
      outs:
        - "data/processed/${item}.csv"
